FROM oven/bun:1 AS builder

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG TURSO_DATABASE_URL
ARG TURSO_AUTH_TOKEN
ARG R2_ACCESS_KEY_ID
ARG R2_SECRET_ACCESS_KEY
ARG R2_ENDPOINT
ARG R2_BUCKET
ARG R2_PUBLIC_URL
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
ARG RESEND_TO_EMAIL

ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET \
    BETTER_AUTH_URL=$BETTER_AUTH_URL \
    TURSO_DATABASE_URL=$TURSO_DATABASE_URL \
    TURSO_AUTH_TOKEN=$TURSO_AUTH_TOKEN \
    R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID \
    R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY \
    R2_ENDPOINT=$R2_ENDPOINT \
    R2_BUCKET=$R2_BUCKET \
    R2_PUBLIC_URL=$R2_PUBLIC_URL \
    RESEND_API_KEY=$RESEND_API_KEY \
    RESEND_FROM_EMAIL=$RESEND_FROM_EMAIL \
    RESEND_TO_EMAIL=$RESEND_TO_EMAIL \
    NITRO_PRESET=bun

RUN bun run build

FROM oven/bun:1 AS runner

WORKDIR /app

COPY --from=builder /app/.output ./.output
COPY --from=builder /app/node_modules ./node_modules

RUN mkdir -p /app/data

ENV NODE_ENV=production \
    HOST=0.0.0.0 \
    PORT=3000

EXPOSE 3000

CMD ["bun", ".output/server/index.mjs"]